version: "2"

services:
  api:
    image: fsilvapucci/employees-rest:latest
    container_name: employees-api
    environment: 
      - DB_ENVIRONMENT=db:1521/xe
    depends_on:
      - "db"
    links:
      - "db"
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier 
  db:
    image: fsilvapucci/employee-oracle-db:latest
    container_name: employees-db
    ports: 
      - "1521:1521"
    volumes:
      - "/my/oracle/data:/u01/app/oracle"
    networks:
      - front-tier
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: 